export const ADD_PRODUCT_CART='ADD_PRODUCT_CART';
export const GET_NUMBERS_CART='GET_NUMBERS_CART';


export const INCREASE_QUANTITY='INCREASE_QUANTITY';
export const DECREASE_QUANTITY='DECREASE_QUANTITY';
export const CLEAR_PRODUCT='CLEAR_PRODUCT';
